<Project Sdk="Microsoft.NET.Sdk.Web">
    <ItemGroup>
        <ProjectReference Include="..\CultureWay.Core\CultureWay.Core.csproj" />
        <ProjectReference Include="..\CultureWay\CultureWay.csproj" />
        <ProjectReference Include="..\CultureWay.UI\CultureWay.UI.csproj" />
        <ProjectReference Include="..\CultureWay.PostgreSQL\CultureWay.PostgreSQL.csproj" />
    </ItemGroup>
</Project>
