<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net10.0</TargetFrameworks>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="xunit" />
        <PackageReference Include="xunit.runner.visualstudio">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="FluentAssertions" />
        <PackageReference Include="NSubstitute" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
        <PackageReference Include="Testcontainers.PostgreSql" />
        <PackageReference Include="Npgsql" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\CultureWay.Core\CultureWay.Core.csproj" />
        <ProjectReference Include="..\CultureWay\CultureWay.csproj" />
        <ProjectReference Include="..\CultureWay.UI\CultureWay.UI.csproj" />
        <ProjectReference Include="..\CultureWay.PostgreSQL\CultureWay.PostgreSQL.csproj" />
    </ItemGroup>

</Project>
